from django.test import TestCase
from .models import NumberRow
from django.utils import timezone
from datetime import datetime

class NumberRowTest(TestCase):
    """
    Regular user can create a new number row.
        A shared prefix is either generated or specified by the creator.
        Actual numbers/values are generated by the system.
        Generated values are consistent, without "missing values" in the row.
    Regular user can display a list of number rows.
    Regular user can display a detail page of a number row.
    """

    def tearDown(self):
        pass


    def test_default_values(self):
        number_row = NumberRow()
        number_row.save()
        self.assertGreater(number_row.id, 0, "number_row.id > 0")
        self.assertEqual(number_row.prefix, str(datetime.now().year), "number_row.prefix = str(datetime.now().year)")
        self.assertEqual(number_row.order, 1, "number_row.order = 1")

    def test_given_prefix(self):
        pass







