# Generated by Django 5.1.7 on 2025-04-02 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='NumberRow',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.entity')),
                ('prefix', models.CharField(default="<attribute 'year' of 'datetime.date' objects>", max_length=20)),
                ('order', models.IntegerField()),
            ],
            bases=('invoices.entity',),
        ),
    ]
