# Generated by Django 5.1.7 on 2025-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_entity_numberrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
