# Generated by Django 5.1.7 on 2025-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_entity_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberrow',
            name='prefix',
            field=models.CharField(default='2025', max_length=20),
        ),
    ]
